### ISSUE TITLE
Fix v3.1 VCF release files to use underscore field separators instead of dash

### ISSUE THREAD

**Issue by jkgoodrich** [broadinstitute/gnomad_qc#160] opened 2021-01-14 19:59 UTC
Discussion of problem: https://atgu.slack.com/archives/CNL7NA6H2/p1610571469219300

There are reports of users trying to use tools on the gnomAD v3.1 VCF and running into problems because we replaced some underscores with a `-`. We have decided that we will keep this as is for the HT, but modify the VCF to replace the `-` with `_`. Since we need to remake the v3.1 release VCF to fix the VEP issue, we can also fix this issue at that time.

**Comment by gtiao** [comment] 2021-01-27 16:49
Duplicate of issue opened by Nick: https://github.com/broadinstitute/gnomad_methods/issues/272

Reproducing his notes before closing the other issue:

Hyphenated info keys are incompatible with bcftools query format (samtools/bcftools#1335).

Hyphenated info keys are also not allowed in version 4.3 of the VCF specification (item 8 of section 1.6.1). (Current gnomAD VCFs are version 4.2)

VCF export scripts should validate field names against the regular expression in the VCF spec.

**Closed** 2021-03-02 19:49 UTC
